---
lang: ja
title: "エネルギーミックスと原子力発電"
subtitle: "我が国が進める2050年にカーボンニュートラルを実現させるための課題と、\\\n今後の原子力発電の位置づけについて"
author: "岩田風多"
format: revealjs
code-line-numbers: false
css: main.css
bibliography: reference.bib
---

## {#note}

:::{.r-stack .r-stretch}
このスライドは\
<https://cm-ayf.github.io/slides/energy-science/> \
で公開されています．
:::

## エネルギーミックスと発電コスト[^1] {#energy-mix-and-power-generation-cost-1}

- エネルギーミックス：電力の供給源の組み合わせと\
  その割合
- 発電コスト：電力を発電するために必要な費用
  - 固定費：建設費・廃棄費用
  - 変動費：燃料費・人件費・保守費用
  - その他：政策経費・事故リスク対応コスト

## エネルギーミックスと発電コスト[^1] {#energy-mix-and-power-generation-cost-2}

- エネルギーミックスは**電力需要の特性**と\
  **電源のコスト特性**の兼ね合いで決まる
  - 電力需要の特性：ベースロード，ミドル，ピーク
  - 電源のコスト特性：固定費と変動費の割合，自然変動など
- 系統安定化＝需給バランスを瞬時に取ることが重要
- エネルギーミックスを再生可能エネルギーに\
  傾けることがカーボンニュートラルの実現に必要

[^1]: 参考： @enecho2021costwg1

## 発電コストについて[^2] {#power-generation-cost}

| 電源 | 資本費[^3] | 燃料費[^4] | 運転維持費[^5] |
| --- | --- | --- | --- | --- |
| LNG火力 | 16.9 | 1.96 | 2.50 |
| 石炭火力 | 25.6 | 1.26 | 6.75 |
| 中水力 | 35-95 | - | 1.0-2.1 |
| 太陽光（事業用） | 21.8 | - | 0.48 |
| 原子力 | 46.3 | 1.2 | 2.0 |

[^2]: 参考： @enecho2021costwg8
[^3]: 単位は 万円/kW；建設費・廃棄費用
[^4]: 単位は 万円/MJ；1$ = 110円（2019年）
[^5]: 単位は 万円/kW/年

## エネルギーミックスにおける原子力発電の位置づけ[^2] {#position-of-nuclear-power-generation-in-energy-mix}

- 資本費が少々高いが，燃料費と運転維持費は比較的安い
- 損害費用や安全対策費用が高い
  - 損害費用は福島第一原発事故をもとに算出されている
- ベースロード電源である

## 核融合発電について[^6] {#nuclear-fusion-power-generation-1}

- 水素などの軽い原子がプラズマとなって核融合反応を起こすことで，熱や電力を得る
  - 熱はタービンによって電力に変換する
- 燃料は海から得られるため，加工費を含めても安いと考えられる
- 損害費用は未知数
- ベースロード電源であると考えられる
- 実用化には数十年を待たなければならない

[^6]: 参考： @wired2023no

## 核融合発電について[^7] {#nuclear-fusion-power-generation-2}

- アメリカにおいてだが，資本費は$3000-$7200と試算されている
- 原子力発電が使われなくなれば，核融合発電が重要になってくる
- （私見）原子力発電が占めていた地位を核融合発電が置き換えるようになるのではないか

[^7]: 参考： @schwartz2023value

## まとめ {#summary}

- エネルギーミックスを再生可能エネルギーに\
  傾けることがカーボンニュートラルの実現に必要
- 原子力発電はfeasibleな選択肢であるが，\
  損害費用や安全対策費用が高いため避けられる
- 原子力発電は長期的には核融合発電に置き換えられていくのではないか

## 参考文献 {#reference}

発電コスト検証ワーキンググループの資料の一覧は[こちら](https://www.enecho.meti.go.jp/committee/council/basic_policy_subcommittee/index.html#cost_wg)から確認できる．