---
lang: ja
title: "生物はDNAを「静的解析」するか"
author: "岩田風多"
format: revealjs
code-line-numbers: false
css: main.css
---

## 「静的解析」とは

- コンピュータプログラムの解析手法の一つ
- プログラムを実行せずに、プログラムの振る舞いを調べる
- プログラムの実行によって起こりうるエラーや異常な挙動を事前に検出することができる
- 実行を伴わないため，実際に危険な挙動を起こすことなく，安全に解析できる

## 静的解析を生物に当てはめる

- プログラム：DNA/RNA
- プログラムの実行：転写から翻訳までの過程
- プログラムの振る舞い：生成されるタンパク質の量・機能など
- エラー：異常なタンパク質の生成・生成量異常など

## DNA複製・mRNAへの転写の検証

- DNA複製の際，塩基のミスマッチは訂正される
  - これはDNAポリメラーゼによる
  - mRNAへの転写の際も同様のプロセスにより訂正される
- このプロセスは静的解析に当てはまるか？
  - DNAポリメラーゼはDNAを読み取り，塩基のミスマッチを検出する
  - 解析においてタンパク質を生成しない

## DNA複製・mRNAへの転写の検証：「誤り訂正」

- 「誤り訂正」ではないか？
  - 情報通信において，ビットが反転するなどのエラーを修正するための手法
  - DNAの「意味」に入り込むことなく解析しているため，静的解析より誤り訂正に近い

## mRNAワクチンの作用機序について

- mRNAワクチンは，mRNAを細胞に入れ，スパイクタンパク質を合成させることで機能する
  - ここで，細胞がmRNAを特段解析せずに翻訳していることに注目
  - 外部から入ってきたmRNAからタンパク質を生成することは危険である
  - この危険性を解析することなく，タンパク質を生成している
- これは，細胞がmRNAを静的解析することはできないことを示唆している？

## 考察

- 細胞はDNAを静的解析していない
  - そのような論文を探し出すことができなかった
- 理由：ハイコストだから？
  - AlphaFoldはタンパク質を生成することなくその構造を予測するが，ハイコストである
  - 構造から挙動を予測することも簡単ではない

## 考察：サンドボックス？

- 細胞は「とりあえずタンパク質を合成してみる」
- プログラミングにおける「サンドボックス」
  - 隔離された環境でプログラムを実行し，外側から危険性を検知する
  - 合成を行っている各細胞がサンドボックスにあたるのではないか

## 考察：サンドボックス？

- 異常な挙動を示している細胞は免疫系に排除される
  - 「サンドボックス」の外部から危険を検知しているということができる
  - また，そのようなタンパク質を記憶し，次に出会ったときは早く検知することができる
